CREATE DATABASE forum;
USE forum;

CREATE TABLE posts (
  id INT(11) NOT NULL AUTO_INCREMENT,
  author VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
